version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  assignees:
  - e-alfred
  - JonathanTreffler
  ignore:
  - dependency-name: css-loader
    versions:
    - 5.1.3
    - 5.1.4
    - 5.2.1
    - 5.2.4
  - dependency-name: "@babel/preset-env"
    versions:
    - 7.12.17
    - 7.13.15
    - 7.13.8
  - dependency-name: "@nextcloud/vue"
    versions:
    - 3.7.1
  - dependency-name: "@babel/core"
    versions:
    - 7.12.17
    - 7.13.0
  - dependency-name: eslint-plugin-promise
    versions:
    - 4.3.0
